// login actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESSFUL = 'LOGIN_REQUEST_SUCCESSFUL';
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR';

// signup actions
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_REQUEST_SUCCESSFUL = 'SIGNUP_REQUEST_SUCCESSFUL';
export const SIGNUP_REQUEST_ERROR = 'SIGNUP_REQUEST_ERROR';

// logout actions
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_REQUEST_SUCCESSFUL = 'LOGOUT_REQUEST_SUCCESSFUL';
export const LOGOUT_REQUEST_ERROR = 'LOGOUT_REQUEST_ERROR';

//Order actions
 
export const ORDER_IN_PROGRESS = "ORDER_IN_PROGRESS";
export const ORDER_DONE = "ORDER_DONE";
export const ORDER_CANCELLED = "ORDER_CANCELLED";
//Otp ations
export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_REQUEST_SUCCESSFUL = "OTP_REQUEST_SUCCESSFUL";
export const OTP_REQUEST_ERROR = "OTP_REQUEST_ERROR";

//OTP confirmation actions
export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESFUL = "VERIFY_OTP_SUCCESFUL";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";
// getServices actions
export const SERVICES_REQUEST = "SERVICES_REQUEST";
export const SERVICES_REQUEST_SUCCESSFUL = 'SERVICES_REQUEST_SUCCESSFUL';
export const SERVICES_REQUEST_ERROR = 'SERVICES_REQUEST_ERROR';


// set selected service action
export const SET_SELECTED_SERVICE = "SET_SELECTED_SERVICE";
export const UNSET_SELECTED_SERVICE = 'UNSET_SELECTED_SERVICE';


// set selected service action
export const SET_FIREBASE_TOKEN = "SET_FIREBASE_TOKEN";
export const SET_FIREBASE_TOKEN_SUCCESSFUL = 'SET_FIREBASE_TOKEN_SUCCESSFUL';
export const SET_FIREBASE_TOKEN_ERROR = 'SET_FIREBASE_TOKEN_ERROR';

//get Orders actions 
export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const GET_NOTIFICATION_SUCCESFUL = 'GET_NOTIFICATION_SUCCESFUL';
export const GET_NOTIFICATION_ERROR = 'GET_NOTIFICATION_ERROR';