backgroundColor: Colors.GRAY,
    width: 130,
    height: 50,
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
    borderBottomEndRadius: 20,
    borderBottomStartRadius: 20,
    marginTop: 20,
    marginEnd:20,